version: '3.8'

services:
  certmate:
    build: .
    container_name: certmate
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
    volumes:
      - ./certificates:/app/certificates
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: certmate-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificates:/etc/nginx/ssl:ro
    depends_on:
      - certmate
    restart: unless-stopped
    profiles:
      - nginx

networks:
  default:
    name: certmate_network
